In [1]:
import pandas as pd

In [2]:
excel_name = 'table3B_satellite_v3.csv'
df3 = pd.read_csv(excel_name)

In [3]:
# Incase you need to remove indexes {nan only}

# df3 = df3.drop(76)

In [4]:
# df3.sort_values(by='Frequency[MHz]', ascending=True)

In [5]:
fs, fe = 1250, 1300

In [6]:
data_n = df3[df3['Frequency[MHz]'] < fe]
data_n = data_n[data_n['Frequency[MHz]'] > fs]
data_n.sort_values(by='Frequency[MHz]', ascending=True)
data_n

,Sys,Band,Signal,Frequency[MHz],Modulation,Rate(MHz),P_t (dBW),G_t (dBi)
25,GAL,E6,CS-D(B),1278.75,BPSK(5),5.1150,15.0,15.0
26,GAL,E6,CS-P(C),1278.75,BPSK(5),5.1150,16.0,15.0
27,GAL,E6,PRS(A),1278.75,"BOCcos(10,5)",5.1150,18.0,16.0
35,BDS-2,B3,RS,1268.52,BPSK(10),10.2300,16.0,16.0
36,BDS-2,B3,RS,1268.52,BPSK(10),10.2300,16.0,16.0
44,BDS-3,B3,B3C-Dm,1268.52,BPSK(10),10.2300,15.0,13.5
45,BDS-3,B3,B3C-Pm,1268.52,BPSK(10),10.2300,15.0,13.5
46,BDS-3,B3,B3A-Dm,1268.52,"BOC(15,2.5)",2.5575,0.0,0.0
47,BDS-3,B3,B3A-Pm,1268.52,"BOC(15,2.5)",2.5575,0.0,0.0
59,QZS-1,L6,L61(LEX)n,1278.75,BPSK(5),5.1150,10.0,10.0
60,QZS-1,L6,L61(LEX)n,1278.75,BPSK(5),5.1150,10.0,10.0
61,QZS-1,L6,L62o,1278.75,BPSK(5),5.1150,10.0,10.0
62,QZS-1,L6,L62o,1278.75,BPSK(5),5.1150,10.0,10.0

In [7]:
# # Searching for satellite by name

# sat = 'SBAS'

# sat_type = df3[df3['Sys'].str.contains(sat)]
# sat_type
# # sat_type.sort_values(by='Index', ascending=True)

In [8]:
# Index for which satellite to obtain

idx = [31,32]
# idx = [20]

# idx = [x for x in range(0, 77, 1)]

In [20]:
# # Power or gain

for i in idx:
    df3.loc[i, 'P_t (dBW)'] = 7
    df3.loc[i, 'G_t (dBi)'] = 7



# # Change the frequency values

# for i in idx:
#     df3.loc[i, 'Frequency[MHz]'] = 1248.3

In [21]:
# df3[df3['Sys'].str.contains(sat)]

data_n = df3[df3['Frequency[MHz]'] < fe]
data_n = data_n[data_n['Frequency[MHz]'] > fs]
data_n.sort_values(by='Frequency[MHz]', ascending=True)

,Sys,Band,Signal,Frequency[MHz],Modulation,Rate(MHz),P_t (dBW),G_t (dBi)
11,GPS,L5,L5I,1176.450,BPSK(10),10.2300,18.0,18.0
12,GPS,L5,L5Q,1176.450,BPSK(10),10.2300,18.0,18.0
31,GAL,E5a,E5a-D,1176.450,"AltBOC(15,10)",10.2300,6.0,6.0
32,GAL,E5a,E5a-P,1176.450,"AltBOC(15,10)",10.2300,6.0,6.0
51,BDS-3,B2,B2a-Dl,1176.450,"TD-AltBOC(15,10)",10.2300,0.0,0.0
52,BDS-3,B2,B2a-Pl,1176.450,"TD-AltBOC(15,10)",10.2300,0.0,0.0
63,QZS-1,L5,L5I,1176.450,BPSK(10),10.2300,16.0,16.0
64,QZS-1,L5,L5Q,1176.450,BPSK(10),10.2300,16.0,16.0
65,IRNSS,L5,SPS,1176.450,BPSK(1),1.0230,16.0,14.0
66,IRNSS,L5,RS-D,1176.450,"BOC(5,2)",2.0460,18.0,16.0
67,IRNSS,L5,RS-P,1176.450,"BOC(5,2)",2.0460,18.0,16.0
69,SBAS,L5,L5I,1176.450,BPSK(10),10.2300,18.0,16.0
70,SBAS,L5,L5Qq,1176.450,BPSK(10),10.2300,18.0,16.0
28,GAL,E5ab,PRS(A),1191.795,"AltBOC(15,10)",5.1150,0.0,0.0
48,BDS-3,B2,B3A-Pm,1191.795,"TD-AltBOC(15,10)",2.5575,0.0,0.0

In [22]:
df3.to_csv(path_or_buf=excel_name, index=None)

### ------------------------------ END -----------------------------------------

In [ ]:
# print df3.sort_values(by='Frequency[MHz]', ascending=True).to_latex(index=False)

# # print df3.to_latex(index=False)